name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - uses: egordm/gha-yarn-node-cache@v1
    - name: Install JS dependencies
      run: yarn install
    - name: Test
      run: yarn test
    - name: Results
      run: echo "This job's status is ${{ job.status }}."
